### ISSUE TITLE
Release v0.1.6

### ISSUE THREAD

**Issue by raikens1** [raikens1/stratamatch#145]
To-Do: 

- [X] Rename FM to AC plots #128
- [x] Fix bug in auto-strata #144
- [x] Plot updates #137 #83
- [x] Allow user to specify pilot_size #129 
- [x] upgrade split_pilot_set for external use #130
- [x] Include prognostic score as a column in Auto-stratify #135
